services:
  gendatabot-api:
    container_name: api
    build:
      context: ./api
    env_file:
      - ./api/.env
    volumes:
      - ./api:/api
    ports:
      - "8000:8000"
    environment:
      - ENV=dev
    networks:
      - gendatabot-network

  gendatabot-frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "7860:7860"
    volumes:
      - ./frontend:/app
    restart: always
    depends_on:
      - gendatabot-api
    networks:
      - gendatabot-network

networks:
  gendatabot-network:
    driver: bridge